# Copyright (c) 2010 Impinj, Inc.

default:
	cd Example1_QueryFeatures;      $(MAKE)
	cd Example2_QueryTags;          $(MAKE)
	cd Example3_AsyncTags;          $(MAKE)
	cd Example3A_AsyncTags;         $(MAKE)
	cd Example4_GPIO;               $(MAKE)
	cd Example5_SettingsFiles;      $(MAKE)
	cd Example6_DisconnectedOps;    $(MAKE)
	cd Example7_WriteTags;          $(MAKE)
	cd Example8_ManyReaders;        $(MAKE)
	cd Example_GpiTriggeredTags;	$(MAKE)
	cd Example_Gpo;			$(MAKE)
	cd Example_KillTag;		$(MAKE)
	cd Example_PowerRamp;		$(MAKE)
	cd Example_ProgramEpc;		$(MAKE)
	cd Example_ProgramUserMemory;	$(MAKE)
	cd Example_ReadSerializedTid;	$(MAKE)
	cd Example_ReadTagsFilter;	$(MAKE)
	cd Example_ReadUserMemory;	$(MAKE) 
#	cd Template_Cons;               $(MAKE)

all:
	cd Example1_QueryFeatures;      $(MAKE) all
	cd Example2_QueryTags;          $(MAKE) all
	cd Example3_AsyncTags;          $(MAKE) all
	cd Example3A_AsyncTags;         $(MAKE) all
	cd Example4_GPIO;               $(MAKE) all
	cd Example5_SettingsFiles;      $(MAKE) all
	cd Example6_DisconnectedOps;    $(MAKE) all
	cd Example7_WriteTags;          $(MAKE) all
	cd Example8_ManyReaders;        $(MAKE) all
	cd Example_GpiTriggeredTags;	$(MAKE) all
	cd Example_Gpo;			$(MAKE) all
	cd Example_KillTag;		$(MAKE) all
	cd Example_PowerRamp;		$(MAKE) all
	cd Example_ProgramEpc;		$(MAKE) all
	cd Example_ProgramUserMemory;	$(MAKE) all
	cd Example_ReadSerializedTid;	$(MAKE) all
	cd Example_ReadTagsFilter;	$(MAKE) all
	cd Example_ReadUserMemory;	$(MAKE) all
#	cd Template_Cons;               $(MAKE) all

clean:
	cd Example1_QueryFeatures;      $(MAKE) clean
	cd Example2_QueryTags;          $(MAKE) clean
	cd Example3_AsyncTags;          $(MAKE) clean
	cd Example3A_AsyncTags;         $(MAKE) clean
	cd Example4_GPIO;               $(MAKE) clean
	cd Example5_SettingsFiles;      $(MAKE) clean
	cd Example6_DisconnectedOps;    $(MAKE) clean
	cd Example7_WriteTags;          $(MAKE) clean
	cd Example8_ManyReaders;        $(MAKE) clean
	cd Example_GpiTriggeredTags;	$(MAKE) clean
	cd Example_Gpo;			$(MAKE) clean
	cd Example_KillTag;		$(MAKE) clean
	cd Example_PowerRamp;		$(MAKE) clean
	cd Example_ProgramEpc;		$(MAKE) clean
	cd Example_ProgramUserMemory;	$(MAKE) clean
	cd Example_ReadSerializedTid;	$(MAKE) clean
	cd Example_ReadTagsFilter;	$(MAKE) clean
	cd Example_ReadUserMemory;	$(MAKE) clean
#	cd Template_Cons;               $(MAKE) clean

help:
	@echo  ""
	@echo  "make            host build of all examples"
	@echo  "make all        host and reader build of all examples"
	@echo  "make clean      remove all object and executable files"
	@echo  "make help       this help text"
	@echo  ""
